#---------------- Peer0 Org1 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-org1
  name: peer0-org1
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
  - name: "peer-core"
    port: 7051
    targetPort: 7051
  selector:
    app: peer0-org1
---
#---------------- Peer0 Org1 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-org1
  name: peer0-org1-chaincode
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
    - name: "peer-chaincode"
      port: 7052
      targetPort: 7052
  selector:
    app: peer0-org1
---
#---------------- Peer0 Org1 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-org1
    metrics-service: "true"
  name: peer0-org1-metrics
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 11443
    targetPort: 11443
  selector:
    app: peer0-org1
