--- #---------------- Peer0 org1 Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: peer0-org1
  name: peer0-org1
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: peer0-org1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: peer0-org1
    spec:
      containers:
        - args:
            - peer
            - node
            - start
          env:
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
            - name: CORE_PEER_ADDRESS
              value: peer0-org1:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0-org1:7051
            #- name: CORE_PEER_CHAINCODELISTENADDRESS
            #  value: 0.0.0.0:7052
            #- name: CORE_PEER_CHAINCODEADDRESS
            #  value: peer0-org1:7052
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-org1:7051
            - name: CORE_PEER_ID
              value: peer0-org1
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            # /var/run/docker.socket need to be tried
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            #- name: CORE_VM_ENDPOINT
            #  value: http://localhost:2375
            - name: CORE_VM_ENDPOINT   #重点是这里,接收到链码实例化请求，Peer向此地址的Docker发送启动链码容器命令/api调用
              value: tcp://docker:2375
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
          image: hyperledger/fabric-peer:latest
          imagePullPolicy: Never
          name: peer0-org1
          ports:
            - containerPort: 7051
            #- containerPort: 7052
            - containerPort: 7053
            - containerPort: 11443
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric/msp
              name: peer0-org1-claim1
            - mountPath: /etc/hyperledger/fabric/tls
              name: peer0-org1-claim2
            - mountPath: /var/run/docker.sock
              name: dockersock
      restartPolicy: Always
      volumes:
        - name: peer0-org1-claim1
          hostPath:
            path: /hostname/crypto-config/peerOrganizations/org1/peers/peer0-org1/msp
            type: Directory
        - name: peer0-org1-claim2
          hostPath:
            path: /hostname/crypto-config/peerOrganizations/org1/peers/peer0-org1/tls
            type: Directory
        - name: dockersock
          hostPath: 
            path: /var/run/docker.sock
