OrdererOrgs:
  - Name: Orderer
    Domain: consortium
    Specs:
      - Hostname: orderer 
        CommonName: orderer 
PeerOrgs:
  - Name: org1
    Domain: org1
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        CommonName: peer0-org1
    Users:
      Count: 1

  - Name: org2
    Domain: org2
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        CommonName: peer0-org2
    Users:
      Count: 1
