---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-marbles-org2
  namespace: hyperledger
  labels:
    app: chaincode-marbles-org2
spec:
  selector:
    matchLabels:
      app: chaincode-marbles-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-marbles-org2
    spec:
      containers:
        - image: chaincode/marbles:1.0
          name: chaincode-marbles-org2
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAINCODE_CCID
              value: "marbles:cc621a9fe97e796b0f009a82597d70ee83ddf2b8b851fbccf130ffd9ec272736"
            - name: CHAINCODE_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
