---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: docker
  name: docker
  namespace: hyperledger
spec:
  selector:
    name: docker
  ports:
  - protocol: TCP
    targetPort: 2375
    port: 2375

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dind
  namespace: hyperledger
spec:
  replicas: 1
  selector:
    matchLabels:
      name: docker
  template:
    metadata:
      labels:
        name: docker
    spec:
      volumes:
      - name: dockervolume
        emptyDir: {}
      containers:
      - name: docker
        args: ["--registry-mirror=https://4y7mtmnv.mirror.aliyuncs.com", "--registry-mirror=https://registry.docker-cn.com", "--registry-mirror=https://registry.cn-hongkong.aliyuncs.com", "--insecure-registry=192.168.92.151:5000", "--dns=114.114.114.114", "--dns=8.8.8.8"]
        securityContext:
          privileged: true
        image: "docker:18.05.0-dind"
        imagePullPolicy: Never
        ports:
        - containerPort: 2375
        volumeMounts:
        - mountPath: /var/lib/docker
          name: dockervolume
