--- #---------------- Orderer0 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer 
  name: orderer 
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
    - name: "orderer"
      port: 7050
      targetPort: 7050
  selector:
    app: orderer 
---
#---------------- Orderer0 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer 
    metrics-service: "true"
  name: orderer-metrics
  namespace: hyperledger
spec:
  type: ClusterIP
  ports:
    - name: "orderer-metrics"
      port: 8443
      targetPort: 8443
  selector:
    app: orderer 
