--- #---------------- Orderer0 Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orderer 
  name: orderer 
  namespace: hyperledger
spec:
  selector:
    matchLabels:
      app: orderer 
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orderer 
    spec:
      containers:
        - args:
            - orderer
          env:
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_GENESISFILE
              value: /var/hyperledger/orderer/genesis.block
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /var/hyperledger/orderer/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
            - name: ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR
              value: "1"
            - name: ORDERER_KAFKA_VERBOSE
              value: "true"
          image: hyperledger/fabric-orderer:latest
          imagePullPolicy: Never
          name: orderer
          ports:
            - containerPort: 7050
            - containerPort: 10443
          volumeMounts:
            - mountPath: /var/hyperledger/orderer/genesis.block
              name: orderer-claim0
            - mountPath: /var/hyperledger/orderer/msp
              name: orderer-claim1
            - mountPath: /var/hyperledger/orderer/tls
              name: orderer-claim2
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      restartPolicy: Always
      volumes:
        - name: orderer-claim0
          hostPath:
            path: /hostname/channel-artifacts/genesis.block
        - name: orderer-claim1
          hostPath:
            path: /hostname/crypto-config/ordererOrganizations/consortium/orderers/orderer/msp
            type: Directory
        - name: orderer-claim2
          hostPath:
            path: /hostname/crypto-config/ordererOrganizations/consortium/orderers/orderer/tls
            type: Directory
